# Generated by Django 3.1 on 2022-12-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=900)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
